#!/usr/bin/env python

# 초기위치를 현재위치로 설정

import rospy
from geometry_msgs.msg import PoseWithCovarianceStamped

def amcl_pose_callback(msg):
    # AMCL로부터 수신한 위치 메시지를 /initialpose로 발행
    initialpose_pub.publish(msg)

if __name__ == '__main__':
    rospy.init_node('amcl_to_initialpose', anonymous=True)

    # AMCL 위치 메시지 수신을 위한 구독자 설정
    amcl_pose_sub = rospy.Subscriber('/amcl_pose', PoseWithCovarianceStamped, amcl_pose_callback)

    # /initialpose로 위치 메시지를 발행하기 위한 발행자 설정
    initialpose_pub = rospy.Publisher('/initialpose', PoseWithCovarianceStamped, queue_size=10)

    rospy.spin()